import { moduleResolve } from "import-meta-resolve";
import { readFile, unlink } from "node:fs/promises";
import { resolve } from "node:path";
import { pathToFileURL } from "node:url";
import type { NamedApiRoute } from "../router/types";

const WEB_PACKAGE = "@warlock.js/web";
const WEB_BUILD_PACKAGE = "@warlock.js/web/build";
const GENERATED_ROUTE_TYPES = ".warlock/typings/web-routes.d.ts";
const GENERATED_ROUTE_TYPES_HEADER = "// AUTO-GENERATED by @warlock.js/web -- do not edit.";

type WebBuildModule = {
  writeCurrentRouteTypes?: (input: {
    appRoot: string;
    apis: readonly NamedApiRoute[];
  }) => Promise<unknown>;
};

export type RouteTypesPublisherPorts = Readonly<{
  resolveModule: (specifier: string, parent: URL) => URL;
  importModule: (url: URL) => Promise<WebBuildModule>;
}>;

const defaultPorts: RouteTypesPublisherPorts = {
  resolveModule: moduleResolve,
  importModule: async (url) => (await import(url.href)) as WebBuildModule,
};

function isAbsentOptionalWebPackage(thrown: unknown): boolean {
  return (
    typeof thrown === "object" &&
    thrown !== null &&
    "code" in thrown &&
    (thrown as { code?: unknown }).code === "ERR_MODULE_NOT_FOUND" &&
    thrown instanceof Error &&
    thrown.message.includes(`Cannot find package '${WEB_PACKAGE}'`)
  );
}

/**
 * Publish dev route declarations through the consuming app's optional Web
 * build entry. A Core-only app performs no work; an installed but incompatible
 * Web package fails loudly instead of leaving stale generated declarations.
 */
export async function publishCurrentRouteTypes(
  appRoot: string,
  apis: readonly NamedApiRoute[],
  ports: RouteTypesPublisherPorts = defaultPorts,
): Promise<boolean> {
  const projectUrl = pathToFileURL(resolve(appRoot, "package.json"));

  try {
    ports.resolveModule(WEB_PACKAGE, projectUrl);
  } catch (error) {
    if (isAbsentOptionalWebPackage(error)) {
      await clearOwnedRouteTypes(appRoot);
      return false;
    }
    throw error;
  }

  const buildModuleUrl = ports.resolveModule(WEB_BUILD_PACKAGE, projectUrl);
  const buildModule = await ports.importModule(buildModuleUrl);

  if (typeof buildModule.writeCurrentRouteTypes !== "function") {
    throw new Error(
      `${WEB_BUILD_PACKAGE} does not export writeCurrentRouteTypes. Upgrade @warlock.js/web to a compatible version.`,
    );
  }

  await buildModule.writeCurrentRouteTypes({ appRoot, apis });
  return true;
}

/** Remove only this integration's header-proven generated declaration file. */
export async function clearOwnedRouteTypes(appRoot: string): Promise<boolean> {
  const target = resolve(appRoot, GENERATED_ROUTE_TYPES);

  let content: string;
  try {
    content = await readFile(target, "utf8");
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === "ENOENT") return false;
    throw error;
  }

  if (!content.startsWith(GENERATED_ROUTE_TYPES_HEADER)) return false;
  await unlink(target);
  return true;
}
