import { FastifyInstance, getHttpServer, startHttpServer } from "./http/server.mjs";
import { StorageFile } from "./storage/storage-file.mjs";
import { CloudStorageDriverContract, CloudStorageDriverOptions, CloudStorageFileData, DeleteManyResult, EventSubscription, FileVisibility, ListOptions, LocalStorageDriverOptions, PresignedOptions, PresignedUploadOptions, PutDirectoryOptions, PutDirectoryResult, PutOptions, R2StorageDriverOptions, ScopedStorageContract, StorageConfigurations, StorageCopyEventPayload, StorageDriverConfig, StorageDriverContract, StorageDriverName, StorageDriverRegistry, StorageDriverType, StorageEventHandler, StorageEventPayload, StorageEventType, StorageFileData, StorageFileInfo, StorageManagerContract, StoragePutEventPayload, TemporaryTokenError, TemporaryTokenPayload, TemporaryTokenValidation } from "./storage/types.mjs";
import { storageConfig, storageConfigurations } from "./storage/config.mjs";
import { ScopedStorage } from "./storage/scoped-storage.mjs";
import { Storage, storage } from "./storage/storage.mjs";
import { StorageDriverContextStore, storageDriverContext } from "./storage/context/storage-driver-context.mjs";
import { MimeTypes, getMimeType } from "./storage/utils/mime.mjs";
import { CloudDriver, loadS3 } from "./storage/drivers/cloud-driver.mjs";
import { DOSpacesDriver } from "./storage/drivers/do-spaces-driver.mjs";
import { LocalDriver } from "./storage/drivers/local-driver.mjs";
import { R2Driver } from "./storage/drivers/r2-driver.mjs";
import { S3Driver } from "./storage/drivers/s3-driver.mjs";
import { Image, ImageFormat, ImageInput, ImageTransformOptions, WatermarkConfig } from "./image/image.mjs";
import { FileNamingStrategy, ImageTransformCallback, ImageTransformConfig, PrefixConfig, PrefixOptions, SaveAsOptions, SaveOptions, UploadedFileImageOptions, UploadsConfigurations } from "./http/uploads-types.mjs";
import { FileValidationOptions, UploadedFile } from "./http/uploaded-file.mjs";
import { Request } from "./http/request.mjs";
import { CookieOptions, Response, ResponseStatus, SendBufferOptions, SendFileOptions } from "./http/response.mjs";
import { HttpConfigurations, PartialMiddleware, RequestEvent, ResponseEvent, ResponseSSEController, ResponseStreamController, ReturnedResponse } from "./http/types.mjs";
import { defaultHttpConfigurations, httpConfig } from "./http/config.mjs";
import { createHttpApplication, stopHttpApplication } from "./http/createHttpApplication.mjs";
import { RequestLog } from "./http/database/RequestLog.mjs";
import { HttpErrorCodes } from "./http/error-codes.mjs";
import { logResponse, wrapResponseInDataKey } from "./http/events.mjs";
import { RequestController } from "./http/request-controller.mjs";
import { UPLOADS_DEFAULTS, uploadsConfig } from "./http/uploads-config.mjs";
import { BadRequestError, ConflictError, ForbiddenError, HttpError, NotAcceptableError, NotAllowedError, ResourceNotFoundError, ServerError, UnAuthorizedError } from "./http/errors/errors.mjs";
import { CacheMiddlewareOptions } from "./http/middleware/cache-response-middleware.mjs";
import { ConcurrencyLimitOptions } from "./http/middleware/concurrency-limit.middleware.mjs";
import { IdempotencyOptions } from "./http/middleware/idempotency.middleware.mjs";
import { IpFilterOptions } from "./http/middleware/ip-filter.middleware.mjs";
import { MaintenanceOptions } from "./http/middleware/maintenance.middleware.mjs";
import { RateLimitOptions } from "./http/middleware/rate-limit.middleware.mjs";
import { middleware } from "./http/middleware/middleware-list.mjs";
import { createRequestStore, fromRequest, t } from "./http/middleware/inject-request-context.mjs";
import { anyMatch, ipMatches } from "./http/middleware/utils/cidr-match.mjs";
import { buildIdempotencyCacheKey, hashBody, isValidIdempotencyKey } from "./http/middleware/utils/idempotency-key.mjs";
import { parseSize } from "./http/middleware/utils/parse-size.mjs";
import { registerHttpPlugins } from "./http/plugins.mjs";
import { RequestContextStore, requestContext, useCurrentUser, useRequest, useRequestStore } from "./http/context/request-context.mjs";
import { LocalizedObject, getLocalized } from "./utils/get-localized.mjs";
import { ResourceFieldBuilder } from "./resource/resource-field-builder.mjs";
import { Resource, ResourceConstructor, ResourceContract } from "./resource/resource.mjs";
import { ResourceArraySchema, ResourceCastType, ResourceFieldBuilderDateOutputOptions, ResourceFieldConfig, ResourceOutputValueCastType, ResourceSchema, ResourceSelfReference, ResponseBodyValue, ResponseSchema } from "./resource/types.mjs";
import { GroupedRoutesOptions, Middleware, MiddlewareResponse, PartialPick, RequestControllerContract, RequestHandler, RequestHandlerType, RequestHandlerValidation, RequestMethod, ResourceMethod, RestfulMiddleware, Route, RouteOptions, RouteResource, RouterGroupCallback, RouterStacks } from "./router/types.mjs";
import { Router, router } from "./router/router.mjs";
import { app } from "./application/app.mjs";
import { Environment, environment, setEnvironment } from "./utils/environment.mjs";
import { Application } from "./application/application.mjs";
import { AppConfigurations } from "./application/application-config-types.mjs";
import { BenchmarkSnapshots } from "./benchmark/benchmark-snapshots.mjs";
import { BenchmarkProfiler } from "./benchmark/profiler.mjs";
import { BenchmarkChannel, BenchmarkConfigurations, BenchmarkErrorResult, BenchmarkOptions, BenchmarkProfilerOptions, BenchmarkResult, BenchmarkSnapshotsOptions, BenchmarkStats, BenchmarkSuccessResult } from "./benchmark/types.mjs";
import { measure } from "./benchmark/benchmark.mjs";
import { ConsoleChannel } from "./benchmark/channels/console.channel.mjs";
import { NoopChannel } from "./benchmark/channels/noop.channel.mjs";
import { bootstrap } from "./bootstrap.mjs";
import { displayEnvironmentMode } from "./bootstrap/setup.mjs";
import { DatabaseCacheDriver, DatabaseCacheOptions } from "./cache/database-cache-driver.mjs";
import { Connector, ConnectorLifecyclePhase, ConnectorName, ConnectorPriority } from "./connectors/types.mjs";
import { BaseConnector } from "./connectors/base-connector.mjs";
import { CacheConnector } from "./connectors/cache-connector.mjs";
import { HeraldConnector } from "./connectors/herald-connector.mjs";
import { ConnectorsManager, connectorsManager } from "./connectors/connectors-manager.mjs";
import { DatabaseConnector } from "./connectors/database-connector.mjs";
import { HttpConnector } from "./connectors/http-connector.mjs";
import { LoggerConnector } from "./connectors/logger-connector.mjs";
import { MailerConnector } from "./connectors/mail-connector.mjs";
import { SocketConnector } from "./connectors/socket-connector.mjs";
import { StorageConnector } from "./connectors/storage.connector.mjs";
import { CLICommandAction, CLICommandOption, CLICommandOptions, CLICommandPreload, CLICommandSource, CommandActionData, ResolvedCLICommandOption } from "./cli/types.mjs";
import { CLICommand, command } from "./cli/cli-command.mjs";
import { ConfigKey, ConfigKeyRegistry, ConfigName, ConfigRegistry } from "./config/types.mjs";
import { config } from "./config/config-getter.mjs";
import { registerAppConfig } from "./config/config-handlers.mjs";
import { ConfigSpecialHandlers, configSpecialHandlers } from "./config/config-special-handlers.mjs";
import { ContainerTypes, container } from "./container/index.mjs";
import { DatabaseLogModel } from "./database/models/database-log/database-log.mjs";
import { SeedResult, SeederMetadata } from "./database/seeds/types.mjs";
import { Seeder, seeder } from "./database/seeds/seeder.mjs";
import { useComputedModel, useComputedSlug, useHashedPassword } from "./database/utils.mjs";
import { FilesOrchestrator, filesOrchestrator, onCleanup } from "./dev-server/files-orchestrator.mjs";
import { BaseHealthChecker } from "./dev-server/health-checker/checkers/base-health-checker.mjs";
import { EslintHealthChecker } from "./dev-server/health-checker/checkers/eslint-health-checker.mjs";
import { TypescriptHealthChecker } from "./dev-server/health-checker/checkers/typescript-health-checker.mjs";
import { decrypt, encrypt } from "./encryption/encrypt.mjs";
import { hmacHash } from "./encryption/hash.mjs";
import { hashPassword, verifyPassword } from "./encryption/password.mjs";
import { EncryptionConfigurations, EncryptionPasswordConfigurations } from "./encryption/types.mjs";
import { LogConfigurations } from "./logger/types.mjs";
import { setLogConfigurations } from "./logger/logger.mjs";
import { CapturedMail, MailAddress, MailAttachment, MailConfigurations, MailError, MailErrorCode, MailEvents, MailMode, MailOptions, MailPriority, MailResult, MailersConfig, NormalizedMail, SESConfigurations, SMTPConfigurations } from "./mail/types.mjs";
import { getDefaultMailConfig, getMailMode, getMailerConfig, isDevelopmentMode, isProductionMode, isTestMode, resetMailConfig, resolveMailConfig, setMailConfigurations, setMailMode } from "./mail/config.mjs";
import { MAIL_EVENTS, generateMailId, getMailEventName, mailEvents } from "./mail/events.mjs";
import { closeAllMailers, closeMailer, getMailer, getPoolStats, verifyMailer } from "./mail/mailer-pool.mjs";
import { renderReactMail } from "./mail/react-mail.mjs";
import { sendMail } from "./mail/send-mail.mjs";
import { Mail } from "./mail/mail.mjs";
import { assertMailCount, assertMailSent, captureMail, clearTestMailbox, findMailsBySubject, findMailsTo, getLastMail, getMailboxSize, getTestMailbox, wasMailSentTo, wasMailSentWithSubject } from "./mail/test-mailbox.mjs";
import { renderReact } from "./react/index.mjs";
import { RepositoryManager } from "./repositories/repository.manager.mjs";
import { RepositoryAdapterContract } from "./repositories/contracts/repository-adapter.contract.mjs";
import { AllRepositoryOptions, CachedRepositoryOptions, ChunkCallback, CursorPaginationOptions, CursorPaginationResult, FilterFunction, FilterOperator, FilterOptions, FilterRule, FilterRules, PaginationMode, PaginationResult, RepositoryConfigurations, RepositoryEvent, RepositoryOptions, RepositoryOptionsWithCursor, RepositoryOptionsWithPages, SaveMode, TypedAllRepositoryOptions, TypedRepositoryOptions, TypedRepositoryOptionsWithCursor, TypedRepositoryOptionsWithPages, WhereOperator } from "./repositories/contracts/types.mjs";
import { QueryBuilderContract } from "./repositories/contracts/query-builder.contract.mjs";
import { CascadeAdapter } from "./repositories/adapters/cascade/cascade-adapter.mjs";
import { CascadeQueryBuilder } from "./repositories/adapters/cascade/cascade-query-builder.mjs";
import { DefineResourceOptions, defineResource } from "./resource/define-resource.mjs";
import { RegisterResource } from "./resource/register-resource.mjs";
import { Restful } from "./restful/restful.mjs";
import { SocketOptions } from "./socket/types.mjs";
import { getSocketServer } from "./socket/utils.mjs";
import { isTestServerRunning, startHttpTestServer, stopHttpTestServer } from "./tests/start-http-development-server.mjs";
import { expectJson, getTestServerUrl, parseJsonResponse, testDelete, testGet, testPatch, testPost, testPut, testRequest } from "./tests/test-helpers.mjs";
import { setupTest } from "./tests/vitest-setup.mjs";
import { RegisteredUseCase, UseCase, UseCaseAfterMiddleware, UseCaseBeforeMiddleware, UseCaseBroadcastChannel, UseCaseBroadcastEvent, UseCaseBroadcastOption, UseCaseConfigurations, UseCaseContext, UseCaseErrorResult, UseCaseEventsCallbacksMap, UseCaseGuard, UseCaseHandler, UseCaseOnExecutingContext, UseCaseResult, UseCaseRuntimeOptions, UseCaseWithSchema } from "./use-cases/types.mjs";
import { useCase } from "./use-cases/use-case.mjs";
import { broadcastUseCaseResult } from "./use-cases/use-case-broadcast.mjs";
import { fireLifecycleEvent, globalEventsCallbacksMap, globalUseCasesEvents } from "./use-cases/use-case-events.mjs";
import { PipelineOptions, runPipeline } from "./use-cases/use-case-pipeline.mjs";
import { BadSchemaUseCaseError } from "./use-cases/use-case.errors.mjs";
import { $registerUseCase, $unregisterUseCase, addUseCaseHistory, getUseCase, getUseCaseHistory, getUseCases, increaseUseCaseFailedCalls, increaseUseCaseSuccessCalls } from "./use-cases/use-cases-registry.mjs";
import { appLog } from "./utils/app-log.mjs";
import { DatabaseLog, DatabaseLogOptions } from "./utils/database-log.mjs";
import { appPath, cachePath, configPath, logsPath, paths, publicPath, rootPath, sanitizePath, srcPath, storagePath, tempPath, uploadsPath, warlockPath } from "./utils/paths.mjs";
import { promiseAllObject } from "./utils/promise-all-object.mjs";
import { Queue } from "./utils/queue.mjs";
import { sleep } from "./utils/sleep.mjs";
import { sluggable } from "./utils/sluggable.mjs";
import { toJson } from "./utils/to-json.mjs";
import { assetsUrl, publicUrl, setBaseUrl, uploadsUrl, url } from "./utils/urls.mjs";
import { existsExceptCurrentIdRule } from "./validation/database/exists-except-current-id.mjs";
import { existsExceptCurrentUserRule } from "./validation/database/exists-except-current-user.mjs";
import { ExistsExceptCurrentIdRuleOptions, ExistsExceptCurrentUserRuleOptions, UniqueExceptCurrentIdRuleOptions, UniqueExceptCurrentUserRuleOptions } from "./validation/database/types.mjs";
import { uniqueExceptCurrentIdRule } from "./validation/database/unique-except-current-id.mjs";
import { uniqueExceptCurrentUserRule } from "./validation/database/unique-except-current-user.mjs";
import { FileValidator, uploadedFileMetadataSchema } from "./validation/validators/file-validator.mjs";
import { ValidationConfiguration } from "./validation/types.mjs";
import { fileExtensionRule, fileRule, fileTypeRule, imageRule } from "./validation/file/file.mjs";
import { WarlockConfig } from "./warlock-config/types.mjs";
import { defineConfig } from "./warlock-config/define-config.mjs";
import { WarlockConfigManager, warlockConfigManager } from "./warlock-config/warlock-config.manager.mjs";
import { env } from "@mongez/dotenv";
import { colors } from "@mongez/copper";
export * from "@mongez/localization";
export { $registerUseCase, $unregisterUseCase, AllRepositoryOptions, AppConfigurations, Application, BadRequestError, BadSchemaUseCaseError, BaseConnector, BaseHealthChecker, type BenchmarkChannel, type BenchmarkConfigurations, type BenchmarkErrorResult, type BenchmarkOptions, BenchmarkProfiler, type BenchmarkProfilerOptions, type BenchmarkResult, BenchmarkSnapshots, type BenchmarkSnapshotsOptions, type BenchmarkStats, type BenchmarkSuccessResult, CLICommand, CLICommandAction, CLICommandOption, CLICommandOptions, CLICommandPreload, CLICommandSource, CacheConnector, type CacheMiddlewareOptions, CachedRepositoryOptions, type CapturedMail, CascadeAdapter, CascadeQueryBuilder, ChunkCallback, CloudDriver, CloudStorageDriverContract, CloudStorageDriverOptions, CloudStorageFileData, CommandActionData, type ConcurrencyLimitOptions, ConfigKey, ConfigKeyRegistry, ConfigName, ConfigRegistry, ConfigSpecialHandlers, ConflictError, Connector, ConnectorLifecyclePhase, ConnectorName, ConnectorPriority, ConnectorsManager, ConsoleChannel, ContainerTypes, CookieOptions, CursorPaginationOptions, CursorPaginationResult, DOSpacesDriver, DatabaseCacheDriver, type DatabaseCacheOptions, DatabaseConnector, DatabaseLog, DatabaseLogModel, DatabaseLogOptions, DefineResourceOptions, DeleteManyResult, EncryptionConfigurations, EncryptionPasswordConfigurations, Environment, EslintHealthChecker, EventSubscription, ExistsExceptCurrentIdRuleOptions, ExistsExceptCurrentUserRuleOptions, FastifyInstance, FileNamingStrategy, FileValidationOptions, FileValidator, FileVisibility, FilesOrchestrator, FilterFunction, FilterOperator, FilterOptions, FilterRule, FilterRules, ForbiddenError, GroupedRoutesOptions, HeraldConnector, HttpConfigurations, HttpConnector, HttpError, HttpErrorCodes, type IdempotencyOptions, Image, ImageFormat, ImageInput, ImageTransformCallback, ImageTransformConfig, ImageTransformOptions, type IpFilterOptions, ListOptions, LocalDriver, LocalStorageDriverOptions, LocalizedObject, LogConfigurations, LoggerConnector, MAIL_EVENTS, Mail, type MailAddress, type MailAttachment, type MailConfigurations, MailError, type MailErrorCode, type MailEvents, type MailMode, type MailOptions, type MailPriority, type MailResult, MailerConnector, type MailersConfig, type MaintenanceOptions, Middleware, MiddlewareResponse, MimeTypes, NoopChannel, type NormalizedMail, NotAcceptableError, NotAllowedError, PaginationMode, PaginationResult, PartialMiddleware, PartialPick, PipelineOptions, PrefixConfig, PrefixOptions, PresignedOptions, PresignedUploadOptions, PutDirectoryOptions, PutDirectoryResult, PutOptions, QueryBuilderContract, Queue, R2Driver, R2StorageDriverOptions, type RateLimitOptions, RegisterResource, RegisteredUseCase, RepositoryAdapterContract, RepositoryConfigurations, RepositoryEvent, RepositoryManager, RepositoryOptions, RepositoryOptionsWithCursor, RepositoryOptionsWithPages, Request, RequestContextStore, RequestController, RequestControllerContract, RequestEvent, RequestHandler, RequestHandlerType, RequestHandlerValidation, RequestLog, RequestMethod, ResolvedCLICommandOption, Resource, ResourceArraySchema, ResourceCastType, ResourceConstructor, ResourceContract, ResourceFieldBuilder, ResourceFieldBuilderDateOutputOptions, ResourceFieldConfig, ResourceMethod, ResourceNotFoundError, ResourceOutputValueCastType, ResourceSchema, ResourceSelfReference, Response, ResponseBodyValue, ResponseEvent, ResponseSSEController, ResponseSchema, ResponseStatus, ResponseStreamController, Restful, RestfulMiddleware, ReturnedResponse, Route, RouteOptions, RouteResource, Router, RouterGroupCallback, RouterStacks, S3Driver, type SESConfigurations, type SMTPConfigurations, SaveAsOptions, SaveMode, SaveOptions, ScopedStorage, ScopedStorageContract, SeedResult, Seeder, SeederMetadata, SendBufferOptions, SendFileOptions, ServerError, SocketConnector, SocketOptions, Storage, StorageConfigurations, StorageConnector, StorageCopyEventPayload, StorageDriverConfig, StorageDriverContextStore, StorageDriverContract, StorageDriverName, StorageDriverRegistry, StorageDriverType, StorageEventHandler, StorageEventPayload, StorageEventType, StorageFile, StorageFileData, StorageFileInfo, StorageManagerContract, StoragePutEventPayload, TemporaryTokenError, TemporaryTokenPayload, TemporaryTokenValidation, TypedAllRepositoryOptions, TypedRepositoryOptions, TypedRepositoryOptionsWithCursor, TypedRepositoryOptionsWithPages, TypescriptHealthChecker, UPLOADS_DEFAULTS, UnAuthorizedError, UniqueExceptCurrentIdRuleOptions, UniqueExceptCurrentUserRuleOptions, UploadedFile, UploadedFileImageOptions, UploadsConfigurations, UseCase, UseCaseAfterMiddleware, UseCaseBeforeMiddleware, UseCaseBroadcastChannel, UseCaseBroadcastEvent, UseCaseBroadcastOption, UseCaseConfigurations, UseCaseContext, UseCaseErrorResult, UseCaseEventsCallbacksMap, UseCaseGuard, UseCaseHandler, UseCaseOnExecutingContext, UseCaseResult, UseCaseRuntimeOptions, UseCaseWithSchema, ValidationConfiguration, WarlockConfig, WarlockConfigManager, WatermarkConfig, WhereOperator, addUseCaseHistory, anyMatch, app, appLog, appPath, assertMailCount, assertMailSent, assetsUrl, bootstrap, broadcastUseCaseResult, buildIdempotencyCacheKey, cachePath, captureMail, clearTestMailbox, closeAllMailers, closeMailer, colors, command, config, configPath, configSpecialHandlers, connectorsManager, container, createHttpApplication, createRequestStore, decrypt, defaultHttpConfigurations, defineConfig, defineResource, displayEnvironmentMode, encrypt, env, environment, existsExceptCurrentIdRule, existsExceptCurrentUserRule, expectJson, fileExtensionRule, fileRule, fileTypeRule, filesOrchestrator, findMailsBySubject, findMailsTo, fireLifecycleEvent, fromRequest, generateMailId, getDefaultMailConfig, getHttpServer, getLastMail, getLocalized, getMailEventName, getMailMode, getMailboxSize, getMailer, getMailerConfig, getMimeType, getPoolStats, getSocketServer, getTestMailbox, getTestServerUrl, getUseCase, getUseCaseHistory, getUseCases, globalEventsCallbacksMap, globalUseCasesEvents, hashBody, hashPassword, hmacHash, httpConfig, imageRule, increaseUseCaseFailedCalls, increaseUseCaseSuccessCalls, ipMatches, isDevelopmentMode, isProductionMode, isTestMode, isTestServerRunning, isValidIdempotencyKey, loadS3, logResponse, logsPath, mailEvents, measure, middleware, onCleanup, parseJsonResponse, parseSize, paths, promiseAllObject, publicPath, publicUrl, registerAppConfig, registerHttpPlugins, renderReact, renderReactMail, requestContext, resetMailConfig, resolveMailConfig, rootPath, router, runPipeline, sanitizePath, seeder, sendMail, setBaseUrl, setEnvironment, setLogConfigurations, setMailConfigurations, setMailMode, setupTest, sleep, sluggable, srcPath, startHttpServer, startHttpTestServer, stopHttpApplication, stopHttpTestServer, storage, storageConfig, storageConfigurations, storageDriverContext, storagePath, t, tempPath, testDelete, testGet, testPatch, testPost, testPut, testRequest, toJson, uniqueExceptCurrentIdRule, uniqueExceptCurrentUserRule, uploadedFileMetadataSchema, uploadsConfig, uploadsPath, uploadsUrl, url, useCase, useComputedModel, useComputedSlug, useCurrentUser, useHashedPassword, useRequest, useRequestStore, verifyMailer, verifyPassword, warlockConfigManager, warlockPath, wasMailSentTo, wasMailSentWithSubject, wrapResponseInDataKey };