import { beforeAll, describe, expect, it } from "vitest";
import { Image } from "../../../src/image";

/**
 * Image tests run the real `sharp` pipeline over tiny in-memory buffers — no
 * files, no network. If `sharp` is not installed the whole suite is skipped
 * (and reported), since the Image class hard-requires it.
 *
 * Source: core/src/image/image.ts. The pipeline is deferred: chainable methods
 * only enqueue operations; sharp runs at `toBuffer` / `save` / `toBase64` time.
 */

let sharpAvailable = false;
let sharpFn: typeof import("sharp").default;

// A 4x4 red PNG and a 4x4 blue PNG generated by sharp itself in beforeAll.
let redPng: Buffer;

beforeAll(async () => {
  try {
    const module = await import("sharp");
    sharpFn = module.default;
    sharpAvailable = true;
  } catch {
    sharpAvailable = false;
    return;
  }

  redPng = await sharpFn({
    create: { width: 4, height: 4, channels: 3, background: { r: 255, g: 0, b: 0 } },
  })
    .png()
    .toBuffer();
});

describe("Image — pipeline over generated buffers", () => {
  it("reads dimensions of a generated buffer", async () => {
    if (!sharpAvailable) return;

    const image = new Image(redPng);
    const { width, height } = await image.dimensions();

    expect(width).toBe(4);
    expect(height).toBe(4);
  });

  it("resize changes output dimensions", async () => {
    if (!sharpAvailable) return;

    const out = await new Image(redPng).resize({ width: 8, height: 2 }).toBuffer();
    const meta = await sharpFn(out).metadata();

    expect(meta.width).toBe(8);
    expect(meta.height).toBe(2);
  });

  it("format conversion to webp produces webp bytes", async () => {
    if (!sharpAvailable) return;

    const out = await new Image(redPng).format("webp").toBuffer();
    const meta = await sharpFn(out).metadata();

    expect(meta.format).toBe("webp");
  });

  it("apply() runs resize + format in one batch call", async () => {
    if (!sharpAvailable) return;

    const out = await new Image(redPng).apply({ resize: { width: 6 }, format: "png" }).toBuffer();
    const meta = await sharpFn(out).metadata();

    expect(meta.width).toBe(6);
    expect(meta.format).toBe("png");
  });

  it("toBase64 returns a decodable base64 string", async () => {
    if (!sharpAvailable) return;

    const base64 = await new Image(redPng).resize({ width: 2 }).toBase64();
    const meta = await sharpFn(Buffer.from(base64, "base64")).metadata();

    expect(meta.width).toBe(2);
  });

  it("toDataUrl prefixes with the image mime type", async () => {
    if (!sharpAvailable) return;

    const dataUrl = await new Image(redPng).format("png").toDataUrl();

    expect(dataUrl.startsWith("data:image/png;base64,")).toBe(true);
  });
});

describe("Image — deferred pipeline bookkeeping", () => {
  it("queues operations without executing until an output method", () => {
    if (!sharpAvailable) return;

    const image = new Image(redPng).resize({ width: 2 }).rotate(90).blur(1);

    expect(image.getPendingOperationsCount()).toBe(3);
  });

  it("stores quality/format in options", () => {
    if (!sharpAvailable) return;

    const image = new Image(redPng).quality(80).format("webp");

    expect(image.getOptions()).toEqual({ quality: 80, format: "webp" });
  });

  it("clearOperations empties the queue", () => {
    if (!sharpAvailable) return;

    const image = new Image(redPng).resize({ width: 2 }).flip();
    image.clearOperations();

    expect(image.getPendingOperationsCount()).toBe(0);
  });

  it("clone copies operations and options independently", () => {
    if (!sharpAvailable) return;

    const original = new Image(redPng).resize({ width: 2 }).quality(70);
    const cloned = original.clone();

    cloned.rotate(90);

    expect(original.getPendingOperationsCount()).toBe(1);
    expect(cloned.getPendingOperationsCount()).toBe(2);
    expect(cloned.getOptions().quality).toBe(70);
  });
});

describe("Image — validation guards", () => {
  it("rejects quality out of range", () => {
    if (!sharpAvailable) return;

    expect(() => new Image(redPng).quality(0)).toThrow(/between 1 and 100/);
    expect(() => new Image(redPng).quality(101)).toThrow(/between 1 and 100/);
  });

  it("rejects opacity out of range", () => {
    if (!sharpAvailable) return;

    expect(() => new Image(redPng).opacity(-1)).toThrow(/between 0 and 100/);
    expect(() => new Image(redPng).opacity(200)).toThrow(/between 0 and 100/);
  });

  it("rejects a blur sigma below 0.3", () => {
    if (!sharpAvailable) return;

    expect(() => new Image(redPng).blur(0.1)).toThrow(/at least 0.3/);
  });
});
