import { FastifyInstance, getHttpServer, startHttpServer } from "./server.mjs";
import { FileNamingStrategy, ImageTransformCallback, ImageTransformConfig, PrefixConfig, PrefixOptions, SaveAsOptions, SaveOptions, UploadedFileImageOptions, UploadsConfigurations } from "./uploads-types.mjs";
import { FileValidationOptions, UploadedFile } from "./uploaded-file.mjs";
import { Request } from "./request.mjs";
import { CookieOptions, Response, ResponseStatus, SendBufferOptions, SendFileOptions } from "./response.mjs";
import { HttpConfigurations, PartialMiddleware, RequestEvent, ResponseEvent, ResponseSSEController, ResponseStreamController, ReturnedResponse } from "./types.mjs";
import { defaultHttpConfigurations, httpConfig } from "./config.mjs";
import { createHttpApplication, stopHttpApplication } from "./createHttpApplication.mjs";
import { RequestLog } from "./database/RequestLog.mjs";
import { HttpErrorCodes } from "./error-codes.mjs";
import { logResponse, wrapResponseInDataKey } from "./events.mjs";
import { RequestController } from "./request-controller.mjs";
import { UPLOADS_DEFAULTS, uploadsConfig } from "./uploads-config.mjs";
import { BadRequestError, ConflictError, ForbiddenError, HttpError, NotAcceptableError, NotAllowedError, ResourceNotFoundError, ServerError, UnAuthorizedError } from "./errors/errors.mjs";
import { CacheMiddlewareOptions } from "./middleware/cache-response-middleware.mjs";
import { ConcurrencyLimitOptions } from "./middleware/concurrency-limit.middleware.mjs";
import { IdempotencyOptions } from "./middleware/idempotency.middleware.mjs";
import { IpFilterOptions } from "./middleware/ip-filter.middleware.mjs";
import { MaintenanceOptions } from "./middleware/maintenance.middleware.mjs";
import { RateLimitOptions } from "./middleware/rate-limit.middleware.mjs";
import { middleware } from "./middleware/middleware-list.mjs";
import { createRequestStore, fromRequest, t } from "./middleware/inject-request-context.mjs";
import { anyMatch, ipMatches } from "./middleware/utils/cidr-match.mjs";
import { buildIdempotencyCacheKey, hashBody, isValidIdempotencyKey } from "./middleware/utils/idempotency-key.mjs";
import { parseSize } from "./middleware/utils/parse-size.mjs";
import { registerHttpPlugins } from "./plugins.mjs";
import { RequestContextStore, requestContext, useCurrentUser, useRequest, useRequestStore } from "./context/request-context.mjs";