// Auto-generated by Warlock.js - DO NOT EDIT
// One entry per model class that declares `static resource = <Resource>`, so
// `Serialized<Model>` resolves to the resource output. Models whose resource
// cannot be resolved statically are left out.

import "@warlock.js/core";

declare module "@warlock.js/core" {
  interface ModelResourceRegistry {
    "AuditEntry": { model: import("../src/app/users/models/audit-entry.model").default; resource: typeof import("../src/app/users/resources/audit-entry.resource").default };
    "FixtureUser": { model: import("../src/app/users/models/fixture-user.model").FixtureUser; resource: typeof import("../src/app/users/resources/fixture-user.resource").FixtureUserResource };
  }
}
